
dict_request_2 = {'autoSuggestInstance': None,
                  'geocodeFallback': False,
                  'misspellingfallback': False,
                  'moresuggestions': 10,
                  'suggestions': [{'entities': [{'caption': 'Лондон, Англия, Великобритания',
                                                 'destinationId': '549499',
                                                 'geoId': '2114',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.50746,
                                                 'longitude': -0.127673,
                                                 'name': 'Лондон',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'CITY'},
                                                {'caption': 'Лондонский Сити, Лондон, Англия, '
                                                            'Великобритания (City of <span '
                                                            "class='highlighted'>London</span>)",
                                                 'destinationId': '1649988',
                                                 'geoId': '800056',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.515618,
                                                 'longitude': -0.091998,
                                                 'name': 'Лондонский Сити',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'NEIGHBORHOOD'},
                                                {'caption': 'Центральный район Лондона, Лондон, '
                                                            'Англия, Великобритания (Central '
                                                            '<span '
                                                            "class='highlighted'>London</span>)",
                                                 'destinationId': '1735370',
                                                 'geoId': '6195474',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.508362,
                                                 'longitude': -0.129026,
                                                 'name': 'Центральный район Лондона',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'NEIGHBORHOOD'},
                                                {'caption': 'Кингс-Кросс Сент-Панкрасс, Лондон, '
                                                            'Англия, Великобритания',
                                                 'destinationId': '1808499',
                                                 'geoId': '6047476',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.52995251445876,
                                                 'longitude': -0.12402339913938085,
                                                 'name': 'Кингс-Кросс Сент-Панкрасс',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'NEIGHBORHOOD'},
                                                {'caption': 'Паддингтон, Лондон, Англия, '
                                                            'Великобритания',
                                                 'destinationId': '1762406',
                                                 'geoId': '800049',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.515972,
                                                 'longitude': -0.174943,
                                                 'name': 'Паддингтон',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'NEIGHBORHOOD'},
                                                {'caption': 'Виктория, Лондон, Графство Большой '
                                                            'Лондон, Англия, Великобритания',
                                                 'destinationId': '1762415',
                                                 'geoId': '800051',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.495979,
                                                 'longitude': -0.141317,
                                                 'name': 'Виктория',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'NEIGHBORHOOD'}],
                                   'group': 'CITY_GROUP'},
                                  {'entities': [{'caption': '<span '
                                                            "class='highlighted'>London</span> "
                                                            'Hilton on Park Lane, Лондон, '
                                                            'Англия, Великобритания',
                                                 'destinationId': '113142',
                                                 'geoId': '26769',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.505417,
                                                 'longitude': -0.150609,
                                                 'name': 'London Hilton on Park Lane',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'HOTEL'},
                                                {'caption': '<span '
                                                            "class='highlighted'>London</span> "
                                                            'Marriott Hotel Kensington, Лондон, '
                                                            'Англия, Великобритания',
                                                 'destinationId': '114200',
                                                 'geoId': '18773',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.49456,
                                                 'longitude': -0.189412,
                                                 'name': 'London Marriott Hotel Kensington',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'HOTEL'},
                                                {'caption': '<span '
                                                            "class='highlighted'>London</span> "
                                                            'Marriott Hotel Regents Park, '
                                                            'Лондон, Англия, Великобритания',
                                                 'destinationId': '107002',
                                                 'geoId': '4481',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.541848,
                                                 'longitude': -0.170764,
                                                 'name': 'London Marriott Hotel Regents Park',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'HOTEL'}],
                                   'group': 'HOTEL_GROUP'},
                                  {'entities': [{'caption': 'Лондонский мост, Лондон, Англия, '
                                                            'Великобритания',
                                                 'destinationId': '1653378',
                                                 'geoId': '508412',
                                                 'landmarkCityDestinationId': '549499',
                                                 'latitude': 51.50787,
                                                 'longitude': -0.08772,
                                                 'name': 'Лондонский мост',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'LANDMARK'},
                                                {'caption': 'Выставочный центр ExCel, Лондон, '
                                                            'Англия, Великобритания (ExCeL '
                                                            '<span '
                                                            "class='highlighted'>London</span>)",
                                                 'destinationId': '1637201',
                                                 'geoId': '6046590',
                                                 'landmarkCityDestinationId': '549499',
                                                 'latitude': 51.50812517199001,
                                                 'longitude': 0.02979412171967324,
                                                 'name': 'Выставочный центр ExCel',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'LANDMARK'}],
                                   'group': 'LANDMARK_GROUP'},
                                  {'entities': [{'caption': 'Лондон, Великобритания '
                                                            '(LHR-Хитроу)',
                                                 'destinationId': '543878',
                                                 'geoId': '5392460',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.470878,
                                                 'longitude': -0.449753,
                                                 'name': 'Лондон (LHR-Хитроу)',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'AIRPORT'},
                                                {'caption': 'Лондон, Великобритания (LTN-Лютон)',
                                                 'destinationId': '1644476',
                                                 'geoId': '5133388',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.878796,
                                                 'longitude': -0.376453,
                                                 'name': 'Лондон (LTN-Лютон)',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'AIRPORT'},
                                                {'caption': 'Лондон, Великобритания '
                                                            '(STN-Станстед)',
                                                 'destinationId': '1637132',
                                                 'geoId': '5133395',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.889432,
                                                 'longitude': 0.262148,
                                                 'name': 'Лондон (STN-Станстед)',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'AIRPORT'},
                                                {'caption': 'Лондон, Великобритания '
                                                            '(LGW-Гатвик)',
                                                 'destinationId': '543879',
                                                 'geoId': '5719884',
                                                 'landmarkCityDestinationId': None,
                                                 'latitude': 51.156026,
                                                 'longitude': -0.16458,
                                                 'name': 'Лондон (LGW-Гатвик)',
                                                 'redirectPage': 'DEFAULT_PAGE',
                                                 'searchDetail': None,
                                                 'type': 'AIRPORT'}],
                                   'group': 'TRANSPORT_GROUP'}],
                  'term': 'London',
                  'trackingID': 'fe13bf35297f4b07b17dcaf1ca63efd5'}
